kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: {{ .Release.Name }}-auto-update
spec:                          
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: auto-update
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              command: ["oc", "adm", "upgrade", "--to-latest=true"]
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
{{- if eq .Values.serviceAccount.name "" }}
          serviceAccountName: {{ .Release.Name }}
{{- else }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
{{- end }}
