{{- range .Values.certificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
spec:
  secretName: {{ .name }}
  issuerRef:
    name: {{ .issuer | default "letsencrypt-prod" }}
    kind: {{ .kind | default "ClusterIssuer" }}
  dnsNames:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
{{- end }}
