{{- if .Values.cabundle }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ldap-ca
  namespace: {{ .Values.namespace }}
data:
  ca.crt: |
{{ .Values.cabundle | indent 4 }}
{{- end }}
