{{ if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ldap-group-sync
subjects:
  - kind: ServiceAccount
{{- if eq .Values.serviceAccount.name "" }}
    name: {{ .Release.Name }}
{{- else }}
    name: {{ .Values.serviceAccount.name }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-ldap-group-sync
{{- end }}
