kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ldap-config
data:
  {{ .Values.mode }}.txt: |
{{- if eq .Values.mode "blacklist" }}
{{ .Values.blacklist | indent 4 }}
{{- else }}
{{ .Values.whitelist | indent 4 }}
{{- end }}
