kind: CronJob
apiVersion: batch/v1
metadata:
  name: {{ .Release.Name }}-ldap-group-sync
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: ldap-group-sync
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - "/bin/bash"
                - "/etc/scripts/ldap-sync.sh"
              envFrom:
                - configMapRef:
                    name: "{{ .Release.Name }}-ldap-env"
              volumeMounts:
                - mountPath: "/etc/config"
                  name: "ldap-sync-volume"
                - mountPath: "/etc/scripts"
                  name: "ldap-sync-scripts"
                - mountPath: "/tmp/ldap-sync"
                  name: "ldap-sync-workdir"
{{- if .Values.params.bindPassword }}
                - mountPath: "/etc/secrets"
                  name: "ldap-bind-password"
{{- end }}
{{- if .Values.cabundle }}
                - mountPath: "/etc/ldap-ca"
                  name: "ldap-ca"
{{- end }}
          volumes:
            - name: "ldap-sync-volume"
              configMap:
                name: "{{ .Release.Name }}-ldap-config"
            - name: "ldap-sync-scripts"
              configMap:
                name: "{{ .Release.Name }}-ldap-scripts"
                defaultMode: 0555
            - name: "ldap-sync-workdir"
              emptyDir: {}
{{- if .Values.params.bindPassword }}
            - name: "ldap-bind-password"
              secret:
                secretName: "{{ .Release.Name }}-ldap-secret"
{{- end }}
{{- if .Values.cabundle }}
            - name: "ldap-ca"
              configMap:
                name: "{{ .Release.Name }}-ldap-ca"
{{- end }}
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: {{ include "openshift-ldap-sync.serviceAccountName" . }}
