{{- if ne .Values.params.bindPassword "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ldap-secret
type: Opaque
data:
  bindPassword: {{ .Values.params.bindPassword | b64enc }}
{{- end }}
