{{- if .Values.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
{{- if eq .Values.serviceAccount.name "" }}
  name: {{ .Release.Name }}
{{- else }}
  name: {{ .Values.serviceAccount.name }}
{{- end }}
{{- end }}
