{{- if .Values.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "openshift-ldap-sync.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
