# Default values for openshift-autoupdate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: image-registry.openshift-image-registry.svc:5000/openshift/cli
  pullPolicy: Always
  tag: latest

serviceAccount:
  name: openshift-admin
