apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "Helper.name" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  labels:
    {{- include "Helper.labels" . | nindent 4 }}
spec:
  tls:
  - hosts:
      - "{{ tpl .Values.route.host . }}"
    secretName: ingress-tls
  rules:
  - host: "{{ tpl .Values.route.host . }}"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "Helper.name" . }}
            port:
              name: http
  #tls:
  #- hosts:
  #  - "{{ tpl .Values.route.host . }}"
  #  secretName: {{ include "Helper.name" . }}-tls-cert
