apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "Helper.name" . }}
  labels:
    {{- include "Helper.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "Helper.name" . }}
