apiVersion: v1
kind: Service
metadata:
  name: {{ include "shelve.fullname" . }}-backend
  labels:
    {{- include "shelve.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
  selector:
    {{- include "shelve.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
