apiVersion: v2
name: certificate
description: Generic cert-manager Certificate resources
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: Simon Lauger
    email: simon@lauger.de
    url: https://lauger.de

keywords:
  - certificate
  - cert-manager
  - tls
  - letsencrypt

home: https://github.com/slauger/helm-charts
sources:
  - https://github.com/slauger/helm-charts
