apiVersion: v1
kind: Service
metadata:
  name: {{ include "Helper.name" . }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "Helper.name" . }}-tls-cert
  labels:
    {{- include "Helper.labels" . | nindent 4 }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: admin-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: admin
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "Helper.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
