apiVersion: v1
kind: Service
metadata:
  name: {{ include "eibtalio.fullname" . }}-frontend
  labels:
    {{- include "eibtalio.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "eibtalio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
