{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eibtalio.fullname" . }}-frontend
  labels:
    {{- include "eibtalio.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.frontendHost }}
      secretName: {{ .Values.ingress.tls.frontendSecretName | default (printf "%s-frontend-tls" (include "eibtalio.fullname" .)) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.frontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "eibtalio.fullname" . }}-frontend
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eibtalio.fullname" . }}-backend
  labels:
    {{- include "eibtalio.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.backendHost }}
      secretName: {{ .Values.ingress.tls.backendSecretName | default (printf "%s-backend-tls" (include "eibtalio.fullname" .)) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.backendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "eibtalio.fullname" . }}-backend
                port:
                  name: http
{{- end }}
