apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eibtalio.fullname" . }}-secrets
  labels:
    {{- include "eibtalio.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: never
type: Opaque
data:
  jwt-secret-key: {{ randAlphaNum 48 | b64enc | quote }}
  admin-password: {{ randAlphaNum 20 | b64enc | quote }}
